exclude:
  - node_modules
  - backend/node_modules
  - frontend/node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - yarn.lock

  - backend
  - node_modules
  - .gitignore
  - .github
